globalThis.READING_PAGES = [
  {
    id: 'world-recognizes-van-gogh',
    title: "Van Gogh's World",
    kicker: 'A global impression',
    paragraph: 'Starry nights and sunflowers, self-portraits and café settings—all painted in bold, intense colors. Today, people around the world immediately recognize these as the work of Vincent van Gogh, the Dutch painter. Probably no other artist, at any time in any culture, has achieved such popularity. But who was this man and why, even today, do his art and life have such an ability to move us?',
    translation: '星夜与向日葵、自画像与咖啡馆场景——它们全都以大胆而浓烈的色彩绘成。如今，世界各地的人们一眼就能认出，这是荷兰画家文森特·梵高的作品。或许无论在任何时代、任何文化中，都没有其他艺术家获得过如此高的人气。然而，这个人是谁？为什么即使到了今天，他的艺术和人生仍如此打动我们？',
    image: 'assets/reading-page-1.png',
    audio: 'audio/page-1.mp3',
    vocabulary: [
      ['intense', '/ɪnˈtens/', 'adj.', '强烈的；浓烈的', 'having a very strong quality'],
      ['recognize', '/ˈrekəɡnaɪz/', 'v.', '认出；识别', 'to know someone or something because you have seen it before'],
      ['achieved', '/əˈtʃiːvd/', 'v.', '获得；达到', 'succeeded in reaching a result'],
      ['ability', '/əˈbɪləti/', 'n.', '能力', 'the power or skill to do something'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'What do people around the world immediately recognize?',
        choices: ['A French museum', "Van Gogh's paintings", 'A new color technique', 'A famous café owner'],
        answer: 1,
        evidence: '“people around the world immediately recognize these as the work of Vincent van Gogh”',
      },
      {
        level: 'analyze',
        question: 'Why does the paragraph end with two questions about van Gogh?',
        choices: ['To explain how to copy his painting style', 'To compare him with a modern artist', 'To invite readers to explore why his art and life still affect people', 'To list the places where he exhibited paintings'],
        answer: 2,
        evidence: '“why, even today, do his art and life have such an ability to move us?”',
      },
    ],
  },
  {
    id: 'artist-is-born',
    title: 'An Artist Is Born',
    kicker: 'Finding his direction',
    paragraph: 'Vincent van Gogh was born on March 30, 1853, in Zundert, a small village in southern Holland. As a child, he was serious and sensitive. He loved to draw, and his work showed talent, but no one encouraged him to become an artist. Instead, his father thought he should take a “sensible” job—something like a salesclerk or carpenter. As a young adult, he wandered from job to job with little success and very little money, becoming more depressed with each failure. In March 1880, however, just before his 27th birthday, something changed inside van Gogh. He realized that he was meant to be a painter, and he began to study art in Brussels, receiving financial help from his brother Theo.',
    translation: '文森特·梵高于1853年3月30日出生在荷兰南部一个名叫津德尔特的小村庄。孩提时，他严肃而敏感。他喜欢画画，作品也显露出天赋，但没有人鼓励他成为艺术家。相反，他的父亲认为他应该找一份“踏实”的工作——比如售货员或木匠。成年后，他辗转于不同工作之间，既不太成功，也几乎没有钱，并随着每次失败变得更加消沉。可是，1880年3月，就在他27岁生日之前，梵高内心发生了改变。他意识到自己注定要成为画家，于是在弟弟提奥的经济资助下，到布鲁塞尔学习艺术。',
    image: 'assets/reading-page-2.png',
    audio: 'audio/page-2.mp3',
    vocabulary: [
      ['sensitive', '/ˈsensətɪv/', 'adj.', '敏感的；易受伤害的', 'easily affected by feelings or criticism'],
      ['sensible', '/ˈsensəbəl/', 'adj.', '明智的；务实的', 'reasonable and practical'],
      ['wandered', '/ˈwɒndəd/', 'v.', '徘徊；辗转', 'moved from place to place without a clear purpose'],
      ['financial help', '/faɪˈnænʃəl help/', 'phr.', '经济帮助', 'money given to support someone'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'What did van Gogh begin to do after the change in March 1880?',
        choices: ['He became a salesclerk', 'He returned to Zundert', 'He moved to Paris', 'He began to study art in Brussels'],
        answer: 3,
        evidence: '“he began to study art in Brussels, receiving financial help from his brother Theo”',
      },
      {
        level: 'analyze',
        question: 'What can readers infer about Theo from the paragraph?',
        choices: ["He supported Vincent's plan to study art", 'He wanted Vincent to become a carpenter', 'He taught Vincent to draw as a child', 'He sold Vincent’s early paintings'],
        answer: 0,
        evidence: '“receiving financial help from his brother Theo”',
      },
    ],
  },
  {
    id: 'discovering-color',
    title: 'Discovering Color',
    kicker: 'A new way of seeing',
    paragraph: 'In 1886, van Gogh moved to Paris, hoping to learn more about the color techniques being used by Impressionist artists there. Instead of grays and browns, his work began to emphasize blue and red, and then yellow and orange. Soon he began to see life differently: Go slow. Stop thinking. Look around. You’ll see something beautiful if you open yourself. These were the principles that guided his art. With his innovative color combinations, van Gogh wanted to show others how to better appreciate a flower, the night sky, or a person’s face.',
    translation: '1886年，梵高搬到巴黎，希望更多了解那里印象派艺术家所使用的色彩技法。他的作品不再使用灰色和褐色，而开始突出蓝色和红色，随后又使用黄色和橙色。很快，他开始以不同的方式看待生活：放慢脚步，停止思虑，环顾四周。如果你敞开心扉，就会看到美好的事物。这些原则指引着他的艺术。他用富有创新性的色彩组合，想让别人更好地欣赏一朵花、夜空或一张人的脸。',
    image: 'assets/reading-page-3.png',
    audio: 'audio/page-3.mp3',
    vocabulary: [
      ['techniques', '/tekˈniːks/', 'n.', '技巧；技法', 'methods for doing something well'],
      ['emphasize', '/ˈemfəsaɪz/', 'v.', '强调；突出', 'to give special importance to something'],
      ['principles', '/ˈprɪnsəpəlz/', 'n.', '原则', 'basic rules or ideas that guide actions'],
      ['innovative', '/ˈɪnəveɪtɪv/', 'adj.', '创新的', 'using new ideas or methods'],
      ['appreciate', '/əˈpriːʃieɪt/', 'v.', '欣赏；领会', 'to understand the value or beauty of something'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'Which colors did van Gogh’s work begin to emphasize before yellow and orange?',
        choices: ['Blue and red', 'Gray and brown', 'Black and white', 'Green and purple'],
        answer: 1,
        evidence: '“his work began to emphasize blue and red, and then yellow and orange”',
      },
      {
        level: 'analyze',
        question: 'What is the main effect of the short commands “Go slow. Stop thinking. Look around.”?',
        choices: ['They show that Paris was a busy city', 'They explain how to mix paint', 'They suggest a careful, open way of noticing beauty', 'They describe rules at an art school'],
        answer: 3,
        evidence: '“You’ll see something beautiful if you open yourself.”',
      },
    ],
  },
  {
    id: 'descent-into-madness',
    title: 'Descent into Madness',
    kicker: 'Isolation and struggle',
    paragraph: 'Few who lived in van Gogh’s time appreciated his work, however. Many laughed when they saw his paintings, which hurt the sensitive artist terribly. In February 1888, he moved away from Paris to Arles, a town in southern France. Often he could not eat or sleep, and stayed up into the early morning hours painting. Days passed, and he spoke to no one. Following an argument with fellow artist Paul Gauguin, van Gogh took a razor and cut off his own earlobe.',
    translation: '然而，在梵高所处的时代，很少有人欣赏他的作品。许多人看到他的画就嘲笑，这深深伤害了这位敏感的艺术家。1888年2月，他离开巴黎，搬到法国南部小镇阿尔勒。他常常无法吃饭或睡觉，画画一直画到清晨。日子一天天过去，他不和任何人说话。一次与同为艺术家的保罗·高更争吵后，梵高用剃刀割下了自己的耳垂。',
    image: 'assets/reading-page-4.png',
    audio: 'audio/page-4.mp3',
    vocabulary: [
      ['appreciated', '/əˈpriːʃieɪtɪd/', 'v.', '欣赏；赏识', 'understood the value of something'],
      ['sensitive', '/ˈsensətɪv/', 'adj.', '敏感的', 'easily affected by feelings or criticism'],
      ['argument', '/ˈɑːɡjəmənt/', 'n.', '争吵；争论', 'an angry disagreement'],
      ['earlobe', '/ˈɪələʊb/', 'n.', '耳垂', 'the soft lower part of an ear'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'Where did van Gogh move in February 1888?',
        choices: ['Brussels', 'Saint-Rémy', 'Arles', 'Auvers-sur-Oise'],
        answer: 2,
        evidence: '“he moved away from Paris to Arles, a town in southern France”',
      },
      {
        level: 'analyze',
        question: 'Which detail best supports the idea that van Gogh was isolated in Arles?',
        choices: ['He moved from Paris to France', 'He spoke to no one for days', 'He learned color techniques', 'He sold paintings there'],
        answer: 0,
        evidence: '“Days passed, and he spoke to no one.”',
      },
    ],
  },
  {
    id: 'illness-and-creativity',
    title: 'Illness and Creativity',
    kicker: 'Periods of calm',
    paragraph: 'He never explained why he injured himself, but by now, many were convinced that van Gogh was crazy, and, indeed, his mental health started to decline. He began to have attacks during which he would hear strange sounds and think people were trying to hurt him. In the spring of 1889, he was sent to a mental hospital in Saint-Rémy, a town near Arles. What exactly was van Gogh suffering from? No one knows for certain, but some now think it may have been a form of manic depression. Whatever his condition, van Gogh’s illness both inhibited and inspired his creativity. When his attacks came, he could not paint. But during his periods of calm, he was able to complete more than a hundred masterpieces, including the classic The Starry Night. “Working on my pictures,” he wrote, “is almost a necessity for my recovery.”',
    translation: '他从未解释自己为什么会伤害自己，但到这时，许多人相信梵高疯了；确实，他的心理健康开始恶化。他开始出现发作，发作时会听见奇怪的声音，并认为有人想伤害他。1889年春天，他被送往阿尔勒附近圣雷米的一家精神病院。梵高究竟患了什么病？没有人能确定，不过如今有些人认为那可能是一种躁狂抑郁症。无论他的病情是什么，疾病既抑制了他的创造力，也激发了他的创造力。发作时，他无法作画；但在平静期，他能完成一百多幅杰作，其中包括经典作品《星夜》。“画画，”他写道，“几乎是我康复所必需的。”',
    image: 'assets/reading-page-5.png',
    audio: 'audio/page-5.mp3',
    vocabulary: [
      ['decline', '/dɪˈklaɪn/', 'v.', '下降；恶化', 'to become weaker or worse'],
      ['attacks', '/əˈtæks/', 'n.', '发作', 'sudden periods when an illness becomes serious'],
      ['inhibited', '/ɪnˈhɪbɪtɪd/', 'v.', '抑制；阻碍', 'held back or limited something'],
      ['creativity', '/ˌkriːeɪˈtɪvəti/', 'n.', '创造力', 'the ability to produce original ideas'],
      ['masterpieces', '/ˈmɑːstəpiːsɪz/', 'n.', '杰作', 'works of very high quality'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'What was van Gogh able to do during periods of calm?',
        choices: ['Sell every painting he made', 'Return to Paris', 'Stop needing treatment', 'Complete more than a hundred masterpieces'],
        answer: 3,
        evidence: '“during his periods of calm, he was able to complete more than a hundred masterpieces”',
      },
      {
        level: 'analyze',
        question: 'How does the paragraph describe the relationship between illness and creativity?',
        choices: ['His illness had no effect on his art', 'It could limit his painting and also inspire creativity', 'It made every painting easy to finish', 'It explained his financial success'],
        answer: 1,
        evidence: '“van Gogh’s illness both inhibited and inspired his creativity”',
      },
    ],
  },
  {
    id: 'seventy-productive-days',
    title: 'Seventy Productive Days',
    kicker: 'A painting a day',
    paragraph: 'Following his release from the hospital in May 1890, van Gogh took a room in Auvers-sur-Oise, a town just north of Paris. For the 70 days that he lived there, he produced, on average, a painting a day. Until his death, however, he was unable to sell a single one; today, those paintings would be worth more than a billion U.S. dollars.',
    translation: '1890年5月出院后，梵高在巴黎北边的小镇欧韦尔-叙瓦兹租了一个房间。在那里居住的70天里，他平均每天创作一幅画。然而，直到去世，他一幅也没能卖出去；如今，那些画的价值会超过10亿美元。',
    image: 'assets/reading-page-6.png',
    audio: 'audio/page-6.mp3',
    vocabulary: [
      ['release', '/rɪˈliːs/', 'n.', '获释；出院', 'the act of being allowed to leave a place'],
      ['on average', '/ɒn ˈævərɪdʒ/', 'phr.', '平均而言', 'as a usual or typical amount'],
      ['produced', '/prəˈdjuːst/', 'v.', '创作；制作', 'made or created something'],
      ['worth', '/wɜːθ/', 'adj.', '值……钱的；有价值的', 'having a particular value'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'How often did van Gogh produce a painting while he lived in Auvers-sur-Oise?',
        choices: ['About one a day', 'About one a week', 'About one a month', 'About one a year'],
        answer: 0,
        evidence: '“he produced, on average, a painting a day”',
      },
      {
        level: 'analyze',
        question: 'What contrast does the paragraph emphasize?',
        choices: ['He preferred Paris to Auvers-sur-Oise', 'He painted in the morning rather than at night', 'His paintings did not sell during his life but became extremely valuable later', 'He made fewer paintings after leaving the hospital'],
        answer: 2,
        evidence: '“he was unable to sell a single one; today, those paintings would be worth more than a billion U.S. dollars”',
      },
    ],
  },
  {
    id: 'end-of-his-life',
    title: 'The End of His Life',
    kicker: 'An unanswered question',
    paragraph: 'It was at this time that van Gogh either borrowed or stole a gun. On the afternoon of July 27, 1890, he went out to the country and shot himself in the stomach. Two days later, Vincent van Gogh died at age 37. What caused him to take his own life—his lack of financial success, mental illness, loneliness?',
    translation: '就在这时，梵高不是借来就是偷来了一把枪。1890年7月27日下午，他去了乡间，朝自己的腹部开枪。两天后，文森特·梵高在37岁时去世。究竟是什么使他结束自己的生命——经济上的不成功、精神疾病，还是孤独？',
    image: 'assets/reading-page-7.png',
    audio: 'audio/page-7.mp3',
    vocabulary: [
      ['borrowed', '/ˈbɒrəʊd/', 'v.', '借来', 'received something to use temporarily and return later'],
      ['lack', '/læk/', 'n.', '缺乏', 'the absence of something needed'],
      ['financial success', '/faɪˈnænʃəl səkˈses/', 'phr.', '经济上的成功', 'achievement of money-related goals'],
      ['loneliness', '/ˈləʊnlinəs/', 'n.', '孤独', 'the sadness of being alone'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'How old was Vincent van Gogh when he died?',
        choices: ['37', '27', '47', '57'],
        answer: 1,
        evidence: '“Vincent van Gogh died at age 37.”',
      },
      {
        level: 'analyze',
        question: 'What does the final question show about the causes of van Gogh’s death?',
        choices: ['The text says there was only one confirmed cause', 'The text gives a detailed medical diagnosis', 'The text says financial success was the only cause', 'The text presents possible factors without giving a definite answer'],
        answer: 3,
        evidence: '“What caused him to take his own life—his lack of financial success, mental illness, loneliness?”',
      },
    ],
  },
  {
    id: 'van-goghs-legacy',
    title: "Van Gogh's Legacy",
    kicker: 'A story that lives on',
    paragraph: 'Over a century after his death, van Gogh remains extremely popular. His story—of a man who resisted materialism and greed, who was alone and unappreciated—gives people something they need. We find pieces of ourselves in him. This may also explain the high prices paid for van Gogh’s work. His Portrait of Dr. Gachet sold in 1990 for more than $80 million to a Japanese businessman, breaking the world record for a painting. Many of his other works have also sold for millions. Of course, people are buying great art when they purchase one of van Gogh’s paintings, but they are also buying a piece of his story, which, like his work, will live on forever.',
    translation: '在他去世一个多世纪后，梵高仍然极受欢迎。他的故事——一个抵制物质主义和贪婪、孤独且不被欣赏的人——带给人们某种他们需要的东西。我们能在他身上找到自己的一部分。这也许解释了人们为梵高作品支付的高价。1990年，他的《加歇医生的肖像》以8000多万美元卖给一位日本商人，打破了一幅画的世界纪录。他的许多其他作品也卖出了数百万美元。当然，人们购买梵高的一幅画时，是在购买伟大的艺术；但他们也在购买他人生故事的一部分，而那故事会像他的作品一样，永远流传下去。',
    image: 'assets/reading-page-8.png',
    audio: 'audio/page-8.mp3',
    vocabulary: [
      ['resisted', '/rɪˈzɪstɪd/', 'v.', '抵制；抗拒', 'refused to accept or give in to something'],
      ['materialism', '/məˈtɪəriəlɪzəm/', 'n.', '物质主义', 'great importance placed on money and possessions'],
      ['unappreciated', '/ˌʌnəˈpriːʃieɪtɪd/', 'adj.', '未被欣赏的', 'not recognized for value or effort'],
      ['purchase', '/ˈpɜːtʃəs/', 'v.', '购买', 'to buy something'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'Which painting sold for more than $80 million in 1990?',
        choices: ['Portrait of Dr. Gachet', 'The Starry Night', 'A café in Arles', 'A self-portrait from Paris'],
        answer: 0,
        evidence: '“His Portrait of Dr. Gachet sold in 1990 for more than $80 million”',
      },
      {
        level: 'analyze',
        question: 'Why does the paragraph say buyers are also buying “a piece of his story”?',
        choices: ['They are buying art supplies from his studio', 'They are learning his color techniques', 'His life story adds meaning to the artwork for people', 'They are buying tickets to a museum exhibition'],
        answer: 2,
        evidence: '“they are also buying a piece of his story, which, like his work, will live on forever”',
      },
    ],
  },
];
