globalThis.READING_PAGES = [
  {
    title: 'Dragons in the Sky',
    image: 'assets/reading-page-1.png',
    audio: 'audio/page-1.mp3',
    paragraph: `Drake shaded his eyes from the sun. He was standing in the Valley of Clouds behind King Roland’s castle. Not long ago, Drake had never even been to the castle. But now he lived here, and he had an important job. He was a Dragon Master—someone who had been chosen by the Dragon Stone to work with dragons. Above him, three dragons flew in the bright blue sky. Griffith, the wizard who taught the young Dragon Masters, watched as the dragons practiced flying.`,
    translation: `德雷克抬手遮住阳光。他正站在罗兰德国王城堡后面的云之谷。就在不久前，德雷克甚至从未来过城堡。可现在他住在这里，而且肩负着一项重要的工作。他是一名驯龙大师——一个被龙石选中、与龙共事的人。在他上方，三条龙飞翔在明亮的蓝天中。教导年轻驯龙大师的巫师格里菲斯，正看着这些龙练习飞行。`,
    vocabulary: [
      ['shade', '/ʃeɪd/', 'v.', '遮挡', 'to block light from reaching your eyes or body'],
      ['castle', '/ˈkæsəl/', 'n.', '城堡', 'a large strong building where a king or queen may live'],
      ['important', '/ɪmˈpɔːrtənt/', 'adj.', '重要的', 'having great value or meaning'],
      ['choose', '/tʃuːz/', 'v.', '选择', 'to decide which person or thing you want'],
      ['practice', '/ˈpræktɪs/', 'v.', '练习', 'to do something again so that you become better at it'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'Where is Drake standing as the dragons practice flying?',
        choices: ['In the Valley of Clouds', 'Inside a dragon cave', 'Beside his old farm', 'On top of the castle'],
        answer: 0,
        evidence: 'The passage says Drake was standing in the Valley of Clouds behind King Roland’s castle.',
      },
      {
        level: 'analyze',
        question: 'What best shows that Drake’s life has changed?',
        choices: ['He has stopped looking at the sky', 'He has become King Roland’s wizard', 'He now lives at the castle and works with dragons', 'He has returned to his old home'],
        answer: 2,
        evidence: 'The passage contrasts Drake’s earlier life with his new home and important job as a Dragon Master.',
      },
    ],
  },
  {
    title: 'A Sick Dragon',
    image: 'assets/reading-page-2.png',
    audio: 'audio/page-2.mp3',
    paragraph: `Griffith leaned over Kepri, frowning. “I’m afraid she doesn’t look well,” he said. Ana turned to the wizard. “She has seemed a little off since last week—when the tunnel caved in. She gets tired easily. And sometimes her eyes look cloudy. I should have said something!” Griffith put a hand on her shoulder. “It’s not your fault, Ana,” he said. “But are you sure Kepri only started looking sick after that night in the tunnel?” Ana slowly nodded her head. “Yes. She was fine before then.”`,
    translation: `格里菲斯皱着眉，俯身查看凯普莉。“恐怕她看起来不太好。”他说。安娜转向巫师。“从上周隧道塌陷时起，她就显得有点不对劲。她很容易累，有时眼睛看起来还很浑浊。我早该说出来的！”格里菲斯把一只手放在她肩上。“这不是你的错，安娜。”他说，“但你确定凯普莉是在隧道出事的那晚之后才开始显出生病的样子吗？”安娜慢慢地点了点头。“是的。那之前她一直好好的。”`,
    vocabulary: [
      ['frown', '/fraʊn/', 'v.', '皱眉', 'to pull your eyebrows together because you are worried or unhappy'],
      ['seem', '/siːm/', 'v.', '似乎', 'to appear to be a certain way'],
      ['cave in', '/ˌkeɪv ˈɪn/', 'v.', '塌陷', 'to fall inward or down suddenly'],
      ['cloudy', '/ˈklaʊdi/', 'adj.', '浑浊的', 'not clear or bright'],
      ['fault', '/fɔːlt/', 'n.', '过错', 'responsibility for something that went wrong'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'When did Kepri begin to seem unwell?',
        choices: ['After flying over the castle', 'After the tunnel caved in', 'Before Ana met her', 'After Griffith touched her'],
        answer: 1,
        evidence: 'Ana says Kepri has seemed off since the tunnel caved in last week.',
      },
      {
        level: 'analyze',
        question: 'Why does Ana say she should have spoken earlier?',
        choices: ['She wanted to leave the castle', 'She knew how to cure Kepri', 'She had caused the tunnel to fall', 'She had noticed warning signs in Kepri'],
        answer: 3,
        evidence: 'Ana lists Kepri’s tiredness and cloudy eyes, showing that she had already noticed signs of illness.',
      },
    ],
  },
  {
    title: "King Roland's Threat",
    image: 'assets/reading-page-3.png',
    audio: 'audio/page-3.mp3',
    paragraph: `“I understand,” Griffith said. Drake remembered that when the tunnel had caved in, Griffith hadn’t told the king that the Dragon Masters had taken the dragons out. Instead, he said the dragons had tried to escape. Griffith had lied to protect the Dragon Masters. Griffith had only wanted to protect us when he told that lie, Drake thought. But now the king is mad at him instead of us! “So I will ask you again, Griffith,” said the king. “Is one of the dragons sick?”`,
    translation: `“我明白了。”格里菲斯说。德雷克想起，隧道塌陷时，格里菲斯并没有告诉国王，是驯龙大师们把龙带了出去。相反，他说是龙试图逃跑。格里菲斯为了保护驯龙大师们撒了谎。德雷克想：格里菲斯说那个谎，只是想保护我们。可现在国王没有生我们的气，反而在生他的气！“所以，格里菲斯，我再问你一遍，”国王说，“是不是有一条龙病了？”`,
    vocabulary: [
      ['remember', '/rɪˈmembər/', 'v.', '想起', 'to bring something from the past back into your mind'],
      ['escape', '/ɪˈskeɪp/', 'v.', '逃脱', 'to get away from a place or danger'],
      ['lie', '/laɪ/', 'v.', '撒谎', 'to say something that you know is not true'],
      ['protect', '/prəˈtekt/', 'v.', '保护', 'to keep someone safe from harm'],
      ['mad', '/mæd/', 'adj.', '生气的', 'very angry'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'What did Griffith tell the king after the tunnel caved in?',
        choices: ['The Dragon Masters were lost', 'Kepri had flown home', 'The dragons had tried to escape', 'The tunnel was never damaged'],
        answer: 2,
        evidence: 'The passage says Griffith told the king that the dragons had tried to escape.',
      },
      {
        level: 'analyze',
        question: 'Why is the king angry with Griffith instead of the children?',
        choices: ['Griffith lied to protect the Dragon Masters', 'Griffith made a dragon ill', 'Griffith ordered the tunnel closed', 'Griffith refused to teach Drake'],
        answer: 0,
        evidence: 'Drake realizes that Griffith’s protective lie has shifted the king’s anger onto Griffith.',
      },
    ],
  },
  {
    title: "The Wizard's Potion",
    image: 'assets/reading-page-4.png',
    audio: 'audio/page-4.mp3',
    paragraph: `“Keep stirring, Rori,” Griffith said. Rori stirred. The liquid turned blue and started to shine. A soft light came from the pot. Griffith scooped up some liquid with a ladle and put it in a clean jar. “Will this potion make Kepri feel better?” Bo asked. “There’s only one way to find out,” Griffith said. They all walked to Kepri’s cave. Her eyes were closed, and her yellow scales had lost their shine. Griffith handed the jar to Ana. “You are her Dragon Master. She will listen to you. She must drink this,” he said. Ana nodded. She walked up to Kepri. “I have something for you,” she said softly.`,
    translation: `“继续搅拌，萝莉。”格里菲斯说。萝莉继续搅拌。液体变成了蓝色，开始发光。锅里泛出柔和的光。格里菲斯用长柄勺舀起一些液体，倒进一个干净的罐子里。“这种药水能让凯普莉好起来吗？”博问。“只有一种办法能知道。”格里菲斯说。他们一起走向凯普莉的洞穴。她闭着眼睛，黄色的鳞片也失去了光泽。格里菲斯把罐子递给安娜。“你是她的驯龙大师。她会听你的。她必须喝下这个。”他说。安娜点点头，走到凯普莉身边。“我给你带了点东西。”她轻声说。`,
    vocabulary: [
      ['stir', '/stɜːr/', 'v.', '搅拌', 'to move a spoon around in a liquid'],
      ['liquid', '/ˈlɪkwɪd/', 'n.', '液体', 'something that flows and is not solid'],
      ['ladle', '/ˈleɪdəl/', 'n.', '长柄勺', 'a deep spoon with a long handle'],
      ['potion', '/ˈpəʊʃən/', 'n.', '药水', 'a special drink believed to have magical effects'],
      ['shine', '/ʃaɪn/', 'v.', '发光', 'to give off bright light'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'What happens to the potion as Rori stirs it?',
        choices: ['It freezes into ice', 'It becomes black smoke', 'It spills onto the floor', 'It turns blue and shines'],
        answer: 3,
        evidence: 'The liquid turns blue, begins to shine, and gives off a soft light.',
      },
      {
        level: 'analyze',
        question: 'What does Griffith mean when he says there is only one way to find out?',
        choices: ['The recipe can never work', 'He cannot know it works until Kepri drinks it', 'Ana has already tested it', 'Bo should make another potion'],
        answer: 1,
        evidence: 'Griffith answers Bo’s question by taking the potion to Kepri, so testing it on her is how they will learn whether it works.',
      },
    ],
  },
  {
    title: "Ana's Story",
    image: 'assets/reading-page-5.png',
    audio: 'audio/page-5.mp3',
    paragraph: `“Your dad’s adventures sound amazing,” said Drake. “They are.” Ana sighed. “But they’re also dangerous. There are many robbers on the roads. The robbers steal from people who have goods to sell—like our fabrics. And they often steal gold and other treasures from the pyramids. That is why my father did not argue when King Roland’s men came for me. He knew I would be safer elsewhere.” Ana looked sad. Bo was quiet. I guess everyone else is just as homesick as I am, Drake thought.`,
    translation: `“你爸爸的冒险听起来真精彩。”德雷克说。“是的。”安娜叹了口气，“但那里也很危险。路上有很多强盗。他们抢夺那些有货物要卖的人——比如抢我们的布料。他们还经常从金字塔里偷走黄金和其他珍宝。所以罗兰德国王的人来接我时，父亲没有争辩。他知道我去别处会更安全。”安娜看起来很难过。博安静地待着。德雷克想：我想，其他人也和我一样想家。`,
    vocabulary: [
      ['dangerous', '/ˈdeɪndʒərəs/', 'adj.', '危险的', 'likely to hurt someone or cause trouble'],
      ['robber', '/ˈrɑːbər/', 'n.', '强盗', 'a person who steals from people or places'],
      ['goods', '/ɡʊdz/', 'n.', '货物', 'things that are made or grown to be sold'],
      ['treasure', '/ˈtreʒər/', 'n.', '珍宝', 'valuable things such as gold or jewels'],
      ['homesick', '/ˈhəʊmsɪk/', 'adj.', '想家的', 'sad because you are away from home'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'What do the robbers steal from Ana’s people?',
        choices: ['Goods, gold, and treasures', 'Dragons and Dragon Stones', 'Books and healing potions', 'Horses and castle keys'],
        answer: 0,
        evidence: 'Ana says robbers steal goods such as fabrics, as well as gold and treasures from the pyramids.',
      },
      {
        level: 'analyze',
        question: 'What can Drake infer about the Dragon Masters from Ana’s story?',
        choices: ['Only Ana misses her family', 'The Dragon Masters never discuss home', 'They may share homesickness despite coming from different homes', 'Drake wants everyone to leave immediately'],
        answer: 2,
        evidence: 'Ana looks sad, Bo becomes quiet, and Drake realizes that everyone else may be just as homesick as he is.',
      },
    ],
  },
  {
    title: 'Worm Calls',
    image: 'assets/reading-page-6.png',
    audio: 'audio/page-6.mp3',
    paragraph: `How did Worm get out of his cave? Drake wondered. “Worm, what’s wrong?” he asked. Worm nodded toward Kepri. The gate to her cave was open and the Dragon Masters stepped inside. Griffith was asleep in the corner. Books were piled around him. Kepri was asleep, too—but she looked sicker than before. Her scales looked dull. She looked thin and pale. Her breathing was loud and heavy. The Dragon Masters were stunned. “She wasn’t this sick earlier,” Rori said. “Did the potion make her worse?” “Maybe it just didn’t work,” Bo said.`,
    translation: `虫虫是怎么从自己的洞穴里出来的？德雷克心里纳闷。“虫虫，怎么了？”他问。虫虫朝凯普莉点了点头。她洞穴的门开着，驯龙大师们走了进去。格里菲斯睡在角落里，周围堆满了书。凯普莉也睡着了——但她看起来比先前病得更重。她的鳞片暗淡无光，身体又瘦又苍白，呼吸声粗重而响亮。驯龙大师们都惊呆了。“她先前还没病得这么重，”萝莉说，“药水让她更糟了吗？”“也许药水只是没有起作用。”博说。`,
    vocabulary: [
      ['nod', '/nɑːd/', 'v.', '点头', 'to move your head down and up'],
      ['pile', '/paɪl/', 'v.', '堆放', 'to put things on top of one another'],
      ['dull', '/dʌl/', 'adj.', '暗淡的', 'not bright or shiny'],
      ['pale', '/peɪl/', 'adj.', '苍白的', 'having less color than usual'],
      ['stunned', '/stʌnd/', 'adj.', '惊呆的', 'so surprised that you cannot react at once'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'What does Worm do when Drake asks what is wrong?',
        choices: ['He wakes Griffith', 'He nods toward Kepri', 'He closes the cave gate', 'He carries away the books'],
        answer: 1,
        evidence: 'Worm responds by nodding toward Kepri, leading the children to her cave.',
      },
      {
        level: 'analyze',
        question: 'Why do the children question whether the potion worked?',
        choices: ['The potion has disappeared', 'Griffith refuses to make it', 'Worm has become ill too', 'Kepri now looks much sicker'],
        answer: 3,
        evidence: 'Kepri’s dull scales, pale body, and heavy breathing show that her condition has worsened.',
      },
    ],
  },
  {
    title: 'Far-Away Lands',
    image: 'assets/reading-page-7.png',
    audio: 'audio/page-7.mp3',
    paragraph: `“That’s impossible!” said Rori. “Dragons can’t travel halfway across the world using their minds.” “Look around you, Rori,” Bo said. “It must be possible. We are no longer in the Kingdom of Bracken.” “But why didn’t Worm bring Vulcan and Shu with us?” Rori asked. Drake thought back to Kepri’s cave. “We were all touching Worm. And I was touching Kepri. But the other dragons were still in their caves.”`,
    translation: `“这不可能！”萝莉说，“龙不可能用意念穿越半个世界。”“看看你的周围，萝莉，”博说，“这一定是可能的。我们已经不在布拉肯王国了。”“可虫虫为什么没有把瓦肯和舒一起带来？”萝莉问。德雷克回想起凯普莉的洞穴。“我们当时都碰着虫虫，而我还碰着凯普莉。但是另外两条龙仍在各自的洞穴里。”`,
    vocabulary: [
      ['impossible', '/ɪmˈpɑːsəbəl/', 'adj.', '不可能的', 'not able to happen or be done'],
      ['halfway', '/ˌhæfˈweɪ/', 'adv.', '到一半', 'at an equal distance between two places'],
      ['kingdom', '/ˈkɪŋdəm/', 'n.', '王国', 'a country ruled by a king or queen'],
      ['touch', '/tʌtʃ/', 'v.', '触碰', 'to put your hand or body against something'],
      ['mind', '/maɪnd/', 'n.', '意念', 'the part of you that thinks and remembers'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'What proves to Bo that dragons can travel with their minds?',
        choices: ['Vulcan is flying above them', 'Rori has found a new Dragon Stone', 'They are no longer in Bracken', 'The tunnel has opened again'],
        answer: 2,
        evidence: 'Bo points out that the group is no longer in the Kingdom of Bracken.',
      },
      {
        level: 'analyze',
        question: 'Why were Vulcan and Shu probably left behind?',
        choices: ['No one was touching them', 'They refused to help Kepri', 'They were too large to travel', 'They belonged to another kingdom'],
        answer: 0,
        evidence: 'Drake contrasts the dragons being touched with Vulcan and Shu, who remained in their caves.',
      },
    ],
  },
  {
    title: 'A Strange Boy',
    image: 'assets/reading-page-8.png',
    audio: 'audio/page-8.mp3',
    paragraph: `They had no choice. The boy waved for them to follow him. He touched the pyramid. One of the big stones pushed in, revealing an opening. A secret door! Drake thought. “Inside, quick!” the boy said. “Dragons first.” He stepped aside to let them in. Kepri was weak, but Worm nudged her gently with his nose. She stepped through the door. As Drake walked past the boy, he saw a cord around the boy’s neck. Something green and sparkling was dangling from the cord. A Dragon Stone!`,
    translation: `他们别无选择。男孩挥手示意他们跟上。他碰了碰金字塔，其中一块巨石向里陷去，露出一个入口。德雷克心想：一道暗门！“快，进去！”男孩说，“龙先走。”他退到一边让他们进入。凯普莉很虚弱，但虫虫用鼻子轻轻推了推她。她走进门里。德雷克从男孩身边经过时，看见男孩脖子上戴着一根绳子。绳子上悬着一个绿色、闪闪发亮的东西。是一块龙石！`,
    vocabulary: [
      ['reveal', '/rɪˈviːl/', 'v.', '显露', 'to make something hidden become visible'],
      ['opening', '/ˈəʊpənɪŋ/', 'n.', '入口', 'a space that lets someone go through'],
      ['nudge', '/nʌdʒ/', 'v.', '轻推', 'to push gently, often with your hand or nose'],
      ['dangle', '/ˈdæŋɡəl/', 'v.', '悬挂', 'to hang and move freely'],
      ['sparkling', '/ˈspɑːrkəlɪŋ/', 'adj.', '闪闪发亮的', 'shining with many small points of light'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'How does the boy open the secret door?',
        choices: ['He uses Worm’s green light', 'He pulls the cord on his neck', 'He asks Kepri to push it', 'He touches a stone in the pyramid'],
        answer: 3,
        evidence: 'When the boy touches the pyramid, a large stone moves inward and reveals an opening.',
      },
      {
        level: 'analyze',
        question: 'What clue suggests that the boy may be a Dragon Master?',
        choices: ['He knows where the robbers live', 'He wears a Dragon Stone', 'He can lift Kepri by himself', 'He has a book from Griffith'],
        answer: 1,
        evidence: 'Drake sees a green, sparkling Dragon Stone dangling from the boy’s neck.',
      },
    ],
  },
  {
    title: 'Kepri and Wati',
    image: 'assets/reading-page-9.png',
    audio: 'audio/page-9.mp3',
    paragraph: `Drake was starting to figure it out. “So, Kepri must have known that Wati could heal her,” he said. “And she must have told Worm about her twin. That’s how Worm knew to bring her here!” “Is Worm an Earth Dragon?” Heru asked. Drake nodded. “They have amazing powers,” said Heru. “Worm did the right thing when he brought Kepri here.” Rori gave Drake a high five. Ana hugged Worm. “Thank you, Worm!”`,
    translation: `德雷克开始想明白了。“所以，凯普莉一定知道瓦蒂能够治好她，”他说，“而且她一定把自己双胞胎兄弟的事告诉了虫虫。虫虫就是这样知道该把她带到这里来的！”“虫虫是一条大地龙吗？”赫鲁问。德雷克点点头。“大地龙拥有惊人的力量，”赫鲁说，“虫虫把凯普莉带到这里，是做对了。”萝莉和德雷克击了个掌。安娜抱住虫虫。“谢谢你，虫虫！”`,
    vocabulary: [
      ['figure out', '/ˌfɪɡjər ˈaʊt/', 'v.', '弄明白', 'to understand or solve something'],
      ['heal', '/hiːl/', 'v.', '治愈', 'to make someone healthy again'],
      ['twin', '/twɪn/', 'n.', '双胞胎之一', 'one of two children or animals born at the same time'],
      ['power', '/ˈpaʊər/', 'n.', '力量', 'a special ability to do something'],
      ['high five', '/ˌhaɪ ˈfaɪv/', 'n.', '击掌', 'a friendly slap of raised hands to celebrate'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'How did Worm know to bring Kepri to Wati?',
        choices: ['Kepri told him about her twin', 'Heru sent Worm a message', 'Griffith drew Worm a map', 'Rori carried Wati’s Dragon Stone'],
        answer: 0,
        evidence: 'Drake concludes that Kepri told Worm about her twin, who could heal her.',
      },
      {
        level: 'analyze',
        question: 'Why does Heru say Worm did the right thing?',
        choices: ['Worm hid the dragons from the children', 'Worm taught Wati how to fly', 'Worm brought Kepri to someone who could heal her', 'Worm returned alone to Bracken'],
        answer: 2,
        evidence: 'Worm’s journey brought sick Kepri to her twin Wati, whose power could heal her.',
      },
    ],
  },
  {
    title: 'Robbers!',
    image: 'assets/reading-page-10.png',
    audio: 'audio/page-10.mp3',
    paragraph: `When the robbers saw the dragons, they stopped, their eyes wide. Then one of the men started yelling to the others. The men raised their weapons and took aim at the dragons. “They want to capture the dragons!” Ana warned. Wati quickly sprang into action. He shot a black beam of light from his mouth. The beam hit the first robber in the chest and knocked him down. Drake’s heart pounded. He moved closer to Worm. Then the second robber stepped forward. He sent an arrow flying right at Kepri. “No!” Ana cried. Then she jumped in the path of the arrow!`,
    translation: `强盗们看见龙时，全都停住了，眼睛睁得大大的。接着，其中一个人开始朝其他人喊叫。强盗们举起武器，瞄准了龙。“他们想抓住这些龙！”安娜发出警告。瓦蒂迅速行动起来。他从嘴里射出一道黑色光束。光束击中第一个强盗的胸口，把他打倒在地。德雷克的心怦怦直跳。他靠近了虫虫。随后，第二个强盗走上前来。他射出一支箭，直飞向凯普莉。“不！”安娜大喊。接着，她跳到了箭飞来的路线上！`,
    vocabulary: [
      ['capture', '/ˈkæptʃər/', 'v.', '抓住', 'to catch someone or something and keep it'],
      ['weapon', '/ˈwepən/', 'n.', '武器', 'an object used to fight or hurt'],
      ['aim', '/eɪm/', 'v.', '瞄准', 'to point something at a target'],
      ['beam', '/biːm/', 'n.', '光束', 'a straight line of light'],
      ['path', '/pæθ/', 'n.', '路线', 'the line along which something moves'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'What does Wati do when the robbers aim at the dragons?',
        choices: ['He hides behind the pyramid', 'He knocks one robber down with a beam', 'He carries Ana away', 'He opens a secret door'],
        answer: 1,
        evidence: 'Wati shoots a black beam from his mouth and knocks the first robber down.',
      },
      {
        level: 'analyze',
        question: 'What does Ana’s response to the arrow show?',
        choices: ['She wants the robbers to follow her', 'She believes Wati caused the attack', 'She plans to leave Kepri behind', 'She is willing to risk herself to protect Kepri'],
        answer: 3,
        evidence: 'Ana jumps directly into the arrow’s path when it is fired at Kepri.',
      },
    ],
  },
  {
    title: 'Flying',
    image: 'assets/reading-page-11.png',
    audio: 'audio/page-11.mp3',
    paragraph: `The four robbers floated up off the floor. Their legs dangled beneath them. They shouted at Worm. Drake could see the green light in Worm’s eyes starting to flicker. “Worm can’t hold them up there much longer,” he guessed. “We must get out of here!” “Get on the dragons!” Heru yelled. Heru and Rori climbed onto Wati. Ana climbed onto Kepri’s back. Drake and Bo climbed onto Worm. “Wati! Blast the top of the pyramid!” Heru ordered. Wati aimed a black beam of light at the top of the chamber. A bright rainbow ribbon came from Kepri’s mouth and joined it. The top of the pyramid opened up! “Now we fly out,” Heru said. “Go!”`,
    translation: `四个强盗从地面上飘浮起来，双腿悬垂在身下。他们朝虫虫大喊。德雷克看见虫虫眼中的绿光开始闪烁。“虫虫没法让他们在上面再悬空多久了，”他猜测道，“我们必须离开这里！”“骑到龙背上！”赫鲁喊道。赫鲁和萝莉爬上瓦蒂的背，安娜爬上凯普莉的背，德雷克和博则爬上虫虫的背。“瓦蒂！轰开金字塔顶部！”赫鲁命令道。瓦蒂把一道黑色光束瞄准洞室顶部。凯普莉嘴里射出一条明亮的彩虹光带，与黑色光束汇合。金字塔的顶部打开了！“现在我们飞出去，”赫鲁说，“走！”`,
    vocabulary: [
      ['hold', '/həʊld/', 'v.', '托住', 'to keep someone or something in one place'],
      ['climb', '/klaɪm/', 'v.', '爬上', 'to move upward using your hands and feet'],
      ['blast', '/blæst/', 'v.', '轰开', 'to hit or break something with a powerful force'],
      ['chamber', '/ˈtʃeɪmbər/', 'n.', '洞室', 'a room, especially a large or special one'],
      ['ribbon', '/ˈrɪbən/', 'n.', '带状物', 'a long narrow strip that looks like a band'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'How do the dragons open the top of the pyramid?',
        choices: ['Worm pushes the stones apart', 'Heru unlocks another secret door', 'Wati’s beam and Kepri’s ribbon join together', 'The robbers break the ceiling'],
        answer: 2,
        evidence: 'Wati’s black beam and Kepri’s rainbow ribbon meet at the chamber top, which then opens.',
      },
      {
        level: 'analyze',
        question: 'How do Wati and Kepri solve a problem that neither solves alone?',
        choices: ['They combine their different light powers to open the pyramid', 'Wati holds the robbers while Kepri carries Worm', 'Kepri finds the door while Wati calls Griffith', 'They each fly out through a different tunnel'],
        answer: 0,
        evidence: 'Wati’s black beam and Kepri’s rainbow ribbon join before the pyramid opens, showing that their combined powers create the exit.',
      },
    ],
  },
  {
    title: "Ana's Decision",
    image: 'assets/reading-page-12.png',
    audio: 'audio/page-12.mp3',
    paragraph: `Ana sighed. “I am so glad Kepri is better,” she said. “It’s all because of Wati. He knew how to heal her when no one else could. I really think she should stay here with him.” She sounded sad. “But she’s your dragon,” Drake said. “She should stay with you.” Ana shook her head. “I don’t have a strong connection with Kepri. Not like the one that you have with Worm. Your stone glows when you and Worm connect—just like earlier tonight when he called to you. My Dragon Stone has never glowed.”`,
    translation: `安娜叹了口气。“我真高兴凯普莉好起来了，”她说，“这全是瓦蒂的功劳。别人都束手无策时，他知道该怎样治好她。我真的觉得，她应该留在这里陪他。”她的声音里带着难过。“但她是你的龙，”德雷克说，“她应该跟你在一起。”安娜摇了摇头。“我和凯普莉之间没有很强的联系，不像你和虫虫之间那样。你和虫虫心意相通时，你的龙石就会发光——就像今晚早些时候他呼唤你时那样。我的龙石从来没有发过光。”`,
    vocabulary: [
      ['sigh', '/saɪ/', 'v.', '叹气', 'to breathe out slowly because you are sad or tired'],
      ['heal', '/hiːl/', 'v.', '治好', 'to make an injury or illness better'],
      ['connection', '/kəˈnekʃən/', 'n.', '联系', 'a close link or relationship between people or things'],
      ['glow', '/ɡləʊ/', 'v.', '发光', 'to give off a soft steady light'],
      ['earlier', '/ˈɜːrliər/', 'adv.', '早些时候', 'at a time before now or before another event'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'Why does Ana think Kepri should stay with Wati?',
        choices: ['Wati owns Ana’s Dragon Stone', 'Drake ordered Kepri to stay', 'Kepri cannot fly back to Bracken', 'Wati knew how to heal her'],
        answer: 3,
        evidence: 'Ana says Wati healed Kepri when no one else could and believes Kepri should remain with him.',
      },
      {
        level: 'analyze',
        question: 'If Ana’s Dragon Stone begins to glow with Kepri later, what would that most likely mean?',
        choices: ['Kepri has chosen Wati as her only master', 'Ana and Kepri’s connection has grown stronger', 'Worm can no longer hear Drake', 'The stone has lost all of its magic'],
        answer: 1,
        evidence: 'Ana explains that Drake’s stone glows when he and Worm connect, so a glow would signal a stronger connection with Kepri.',
      },
    ],
  },
  {
    title: 'One Last Good-bye',
    image: 'assets/reading-page-13.png',
    audio: 'audio/page-13.mp3',
    paragraph: `“I think I can hear Kepri’s voice…inside my head!” Ana said. Everyone was quiet as Ana listened. She got a smile on her face. She looked up at Kepri flying in the sky. “Kepri wants to come back to be with her brother one day,” Ana said. “Just like I want to come back to my family. But until then, she wants to stay with me in the kingdom of Bracken.” “I’m so happy for you,” said Drake.`,
    translation: `“我想我能听见凯普莉的声音……就在我的脑海里！”安娜说。安娜倾听时，每个人都安静下来。她的脸上露出了笑容。她抬头望着在天空中飞翔的凯普莉。“凯普莉想有一天回到这里，和她的兄弟在一起，”安娜说，“就像我想回到家人身边一样。但在那之前，她想和我一起留在布拉肯王国。”“我真为你高兴。”德雷克说。`,
    vocabulary: [
      ['voice', '/vɔɪs/', 'n.', '声音', 'the sound a person or creature makes when speaking'],
      ['quiet', '/ˈkwaɪət/', 'adj.', '安静的', 'making little or no sound'],
      ['listen', '/ˈlɪsən/', 'v.', '倾听', 'to pay attention to a sound'],
      ['brother', '/ˈbrʌðər/', 'n.', '兄弟', 'a male child who has the same parents as another child'],
      ['kingdom', '/ˈkɪŋdəm/', 'n.', '王国', 'a land ruled by a king or queen'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'What does Kepri want to do for now?',
        choices: ['Stay with Ana in Bracken', 'Remain alone inside the pyramid', 'Return to King Roland without Ana', 'Travel with the robbers'],
        answer: 0,
        evidence: 'Ana hears that Kepri wants to stay with her in Bracken until she can return to her brother one day.',
      },
      {
        level: 'analyze',
        question: 'Why does Ana compare Kepri’s wish with her own?',
        choices: ['Both are afraid to live in Bracken', 'Both want Drake to become their master', 'Both hope to return to family in the future', 'Both have lost their Dragon Stones'],
        answer: 2,
        evidence: 'Kepri hopes to return to her brother, just as Ana hopes to return to her family.',
      },
    ],
  },
  {
    title: 'Home',
    image: 'assets/reading-page-14.png',
    audio: 'audio/page-14.mp3',
    paragraph: `“Will you tell the king about that dark wizard named Maldred?” Bo asked. “There is not much his army can do against Maldred’s dark magic,” Griffith said. “It will be up to us to protect this kingdom.” Rori snorted. “Vulcan won’t be afraid of some old wizard.” “And Vulcan won’t be fighting that wizard alone,” Ana said, looking at Kepri. “All of us will help.” Drake looked at Worm. He was proud of how his dragon had helped Kepri. “Yes,” he said, turning to his friends. “Whatever happens, we’re all in this together!”`,
    translation: `“你会把那个名叫马尔德雷德的黑暗巫师告诉国王吗？”博问。“国王的军队面对马尔德雷德的黑暗魔法也做不了多少事，”格里菲斯说，“保护这个王国要靠我们了。”萝莉哼了一声。“瓦肯才不会害怕什么老巫师。”“而且瓦肯不会独自对付那个巫师，”安娜望着凯普莉说，“我们所有人都会帮忙。”德雷克看着虫虫。他为自己的龙曾经帮助凯普莉而感到骄傲。“是的，”他转向朋友们说，“无论发生什么，我们都会一起面对！”`,
    vocabulary: [
      ['army', '/ˈɑːrmi/', 'n.', '军队', 'a large group of soldiers'],
      ['magic', '/ˈmædʒɪk/', 'n.', '魔法', 'a mysterious power that makes unusual things happen'],
      ['protect', '/prəˈtekt/', 'v.', '保护', 'to keep a person or place safe'],
      ['afraid', '/əˈfreɪd/', 'adj.', '害怕的', 'feeling fear or worry'],
      ['together', '/təˈɡeðər/', 'adv.', '一起', 'with one another in the same group'],
    ],
    questions: [
      {
        level: 'understand',
        question: 'Who will help protect the kingdom from Maldred?',
        choices: ['Maldred’s army by itself', 'The Dragon Masters and their dragons', 'The robbers from the pyramid', 'Ana’s father and the traders'],
        answer: 1,
        evidence: 'Griffith says protection is up to them, and Ana adds that all of them will help.',
      },
      {
        level: 'analyze',
        question: 'What main idea does Drake’s final statement express?',
        choices: ['Dragons should solve every problem alone', 'The kingdom is safe from all magic', 'Drake no longer needs Worm’s help', 'Friends face future dangers as a team'],
        answer: 3,
        evidence: 'Drake says that whatever happens, they are all in it together.',
      },
    ],
  },
];
