globalThis.READING_CATALOG = [{
  id: 'rise-of-the-earth-dragon',
  title: 'Rise of the Earth Dragon',
  titleZh: '大地之龙的崛起',
  description: '少年德雷克离开洋葱农场，第一次发现龙真实存在。',
  grade: '小学高年级',
  level: '初级',
  pages: 8,
  cover: 'books/rise-of-the-earth-dragon/assets/cover.png',
  href: 'reader.html?book=rise-of-the-earth-dragon',
}, {
  id: 'saving-the-sun-dragon',
  title: 'Saving the Sun Dragon',
  titleZh: '拯救太阳龙',
  description: '太阳龙 Kepri 突然病倒，Dragon Masters 踏上寻找真相与救援伙伴的冒险。',
  grade: '小学高年级',
  level: '初级',
  pages: 14,
  cover: 'books/saving-the-sun-dragon/assets/cover.png',
  href: 'reader.html?book=saving-the-sun-dragon',
}, {
  id: 'a-musical-boost',
  title: 'A Musical Boost',
  titleZh: '音乐给大脑的助力',
  description: '探索音乐如何提升听力、专注力、语言能力，并帮助大脑恢复表达。',
  grade: '小学高年级',
  level: 'RE Level 1',
  pages: 8,
  cover: 'books/a-musical-boost/assets/cover.png',
  textbook: 'READING EXPLORER 1 · THIRD EDITION',
  textbookCover: 'books/a-musical-boost/assets/textbook-cover.gif',
  theme: 'reading-explorer-1',
  href: 'reader.html?book=a-musical-boost',
}, {
  id: 'van-goghs-world',
  title: "Van Gogh's World",
  titleZh: '梵高的世界',
  textbook: 'READING EXPLORER 3 · THIRD EDITION',
  grade: '初中',
  level: 'RE Level 3',
  difficulty: '进阶',
  pages: 8,
  cover: 'books/van-goghs-world/assets/cover.png',
  textbookCover: 'books/van-goghs-world/assets/textbook-cover.webp',
  description: '走进梵高的色彩、挣扎、创造力与永恒艺术遗产。',
}];
